### ISSUE TITLE
Values provided to tf.concat do not have same shape

### ISSUE THREAD

**Issue by ambrishrawat** [kuza55/keras-extras#2]
tf.concat in get_slice is provided with tensors of different shape and also dtype. 
I was trying to get it to work for the cifar10_cnn.py from keras examples.

**Comment by kuza55** [comment]
Could you post a gist of what you're doing and the actual error you see?

**Comment by ambrishrawat** [comment]
Hi,

Sorry for the late response. But this is the gist of what I am doing and the error I get

`model = Sequential()

#...model defintion

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

#...load training and test set

from multi_gpu import *
model = make_parallel(model,gpu_count=2)

model.fit(X_train, Y_train,
              batch_size=batch_size,
              nb_epoch=nb_epoch,
              validation_data=(X_test, Y_test),
              shuffle=True)
`

The error is this

`
Traceback (most recent call last):
  File "./cifar10_cnn.py", line 83, in <module>
    model = make_parallel(model,gpu_count=2)
  File "...", line 28, in make_parallel
    slice_n = Lambda(get_slice, output_shape=input_shape, arguments={'idx':i,'parts':gpu_count})(x)
  .
  .
  .
  File "<path>/tensorflow/python/framework/tensor_shape.py", line 570, in merge_with
    (self, other))
  ValueError: Shapes (2,) and () are not compatible
`

**Comment by xinkwang** [comment]
I am running into a similar problem, but I am running the code on python3.5. 

> Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 435, in apply_op
    as_ref=input_arg.is_ref)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 730, in convert_n_to_tensor
    preferred_dtype=preferred_dtype))
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 583, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype float64 for Tensor with dtype int32: 'Tensor("tower_0/strided_slice_1:0", shape=(1,), dtype=int32, device=/device:GPU:0)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../test_codes/test_make_parallel.py", line 17, in <module>
    model = make_parallel(model, 4)
  File "/src/test_codes/multi_gpu.py", line 29, in make_parallel
    slice_n = Lambda(get_slice, output_shape=input_shape, arguments={'idx':i,'parts':gpu_count})(x)
  File "/src/keras/engine/topology.py", line 569, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/src/keras/engine/topology.py", line 632, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/src/keras/engine/topology.py", line 164, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/src/keras/layers/core.py", line 596, in call
    return self.function(x, **arguments)
  File "/src/test_codes/multi_gpu.py", line 11, in get_slice
    size = tf.concat(0, [ shape[:1]/parts, shape[1:] ])
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1005, in concat
    name=name)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 438, in _concat
    values=values, name=name)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 463, in apply_op
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'Concat' Op have types [float64, int32] that don't all match.

**Comment by ambrishrawat** [comment]
I am running on 3.5 as well

**Comment by dspavankumar** [comment]
@xinkwang I had the same issue. Casting the tensors into int32 in multi_gpu.py lines 10 and 11 solved the issue:
size = tf.concat(0, [ tf.cast(shape[:1]/parts, tf.int32), tf.cast(shape[1:], tf.int32) ])
stride = tf.concat(0, [ tf.cast(shape[:1]/parts, tf.int32) , tf.cast(shape[1:]*0, tf.int32) ])

**Comment by kuza55** [comment]
I merged a commit to support Python3 in make_parallel; it sounds like it may resolve your issues: https://github.com/kuza55/keras-extras/commit/95d00a1aead704e273e2ad693000c2cd256550fd

**Comment by ybzhou** [comment]
@ambrishrawat @kuza55 I got the same error when trying to run the example given in the blog.

**Comment by irwenqiang** [comment]
@ybzhou Did you solve your problem? I got the same error.

**Comment by beeva-enriqueotero** [comment]
It seems related to https://github.com/kuza55/keras-extras/issues/8

**Comment by ambrishrawat** [comment]
Yeah that solved it for me
